# Generated by Django 5.0.4 on 2024-05-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='page',
            field=models.CharField(max_length=50),
        ),
    ]
