# Generated by Django 5.0.4 on 2024-05-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='request',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.CharField(max_length=1000),
        ),
    ]
