# Generated by Django 5.0.4 on 2024-05-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='labels',
            field=models.ManyToManyField(blank=True, to='chat.label'),
        ),
    ]
