# Generated by Django 5.0.4 on 2024-05-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='label',
        ),
    ]
