# Generated by Django 5.0.4 on 2024-05-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_chat_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.CharField(max_length=10000),
        ),
    ]
