# Generated by Django 5.0.4 on 2024-06-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tokens',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='chat',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='chats', to='chat.label'),
        ),
    ]
