# Generated by Django 5.0.4 on 2024-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_message_tokens_alter_chat_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='tokens',
            new_name='output_tokens',
        ),
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.IntegerField(default=200),
        ),
    ]
