entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: ge63kin@mytum.de
      storage: acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: true
